### PR TITLE
Hg assets

### PR DESCRIPTION
**Pull request by hgmnz**
Skip download and flushing when hitting `/assets` in dev mode.

### CODE REVIEW

**Comment by croaky** [comment]
Harold, do you think this solves the slowdown we saw this week? If so, awesome work.

**Comment by hgmnz** [comment]
It does, tried it on our current project by bundling the local gem. _¡Funciona bien!_

**Comment by jferris** [comment]
Nice work, Harold. We'll get this merged and released.

**Comment by joshuaclayton** [comment]
This has been merged into master. v1.1.2 of the gem includes this fix.

**Pull request closed without merging**
